title: ASL, Oh-so-swell!

# theme: jekyll-theme-midnight
remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Automated Sign Language on GitHub":
    - "//github.com/jmuss07/Automated-Sign-Language"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true